# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '01.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5.QtCore import QRect, QMetaObject, QCoreApplication
from PyQt5.QtWidgets import QWidget, QPushButton, QLabel, QTextEdit, QMenuBar, QApplication, QStatusBar, QMainWindow


class Point:
    def __init__(self, sh, distance):
        self.sh_point = sh
        self.distance_point = distance

    def change(self, sh, distance):
        self.sh_point = sh
        self.distance_point = distance


lst = [Point(248, 21), Point(120, 49), Point(504, 48)]


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(840, 407)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.button_edit = QPushButton(self.centralwidget)
        self.button_edit.setObjectName(u"button_edit")
        self.button_edit.setGeometry(QRect(410, 180, 151, 31))
        self.sh = QTextEdit(self.centralwidget)
        self.sh.setObjectName(u"sh")
        self.sh.setGeometry(QRect(470, 140, 41, 31))
        self.distance = QTextEdit(self.centralwidget)
        self.distance.setObjectName(u"distance")
        self.distance.setGeometry(QRect(520, 140, 41, 31))
        self.button_save = QPushButton(self.centralwidget)
        self.button_save.setObjectName(u"button_save")
        self.button_save.setGeometry(QRect(410, 220, 151, 31))
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(410, 80, 151, 21))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(680, 50, 91, 21))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(680, 80, 91, 21))
        self.sh_2 = QTextEdit(self.centralwidget)
        self.sh_2.setObjectName(u"sh_2")
        self.sh_2.setGeometry(QRect(410, 140, 51, 31))
        self.sh_14 = QTextEdit(self.centralwidget)
        self.sh_14.setObjectName(u"sh_14")
        self.sh_14.setGeometry(QRect(10, 290, 101, 21))
        self.sh_15 = QTextEdit(self.centralwidget)
        self.sh_15.setObjectName(u"sh_15")
        self.sh_15.setGeometry(QRect(120, 290, 101, 21))
        self.sh_16 = QTextEdit(self.centralwidget)
        self.sh_16.setObjectName(u"sh_16")
        self.sh_16.setGeometry(QRect(230, 290, 101, 21))
        self.sh_17 = QTextEdit(self.centralwidget)
        self.sh_17.setObjectName(u"sh_17")
        self.sh_17.setGeometry(QRect(340, 290, 101, 21))
        self.sh_18 = QTextEdit(self.centralwidget)
        self.sh_18.setObjectName(u"sh_18")
        self.sh_18.setGeometry(QRect(450, 290, 101, 21))
        self.sh_19 = QTextEdit(self.centralwidget)
        self.sh_19.setObjectName(u"sh_19")
        self.sh_19.setGeometry(QRect(560, 290, 101, 21))
        self.sh_20 = QTextEdit(self.centralwidget)
        self.sh_20.setObjectName(u"sh_20")
        self.sh_20.setGeometry(QRect(670, 290, 101, 21))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(680, 110, 91, 21))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(680, 140, 91, 21))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(430, 120, 21, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(490, 120, 21, 16))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(530, 120, 51, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 840, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.button_edit.setText(QCoreApplication.translate("MainWindow",
                                                            u"\u0420\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u0442\u044c",
                                                            None))
        self.button_save.setText(
            QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow",
                                                           u"\u041a \u043f\u0435\u0440\u0432\u043e\u043c\u0443 \u0434\u043d\u044e",
                                                           None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow",
                                                             u"\u041a \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u043c\u0443",
                                                             None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow",
                                                             u"\u041a \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u043c\u0443 \u0434\u043d\u044e",
                                                             None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow",
                                                             u"\u041a \u043f\u0440\u0435\u0434\u044b\u0434\u0443\u0449\u0435\u043c\u0443 \u0434\u043d\u044e",
                                                             None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"id", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"sh", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"distance", None))
    # retranslateUi


class MyWidget(QMainWindow, Ui_MainWindow):

    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.button_edit.clicked.connect(self.run_edit)
        self.button_save.clicked.connect(self.run_save)

    def run_save(self):
        self.a = Window()
        self.a.show()

    def run_edit(self):
        global lst
        sh_text = self.sh.toPlainText()
        print(sh_text)
        distance_text = self.distance.toPlainText()
        try:
            for i in sh_text:
                i = int(i)
            for i in distance_text:
                i = int(i)
            lst.append(Point(sh_text, distance_text))
        except:
            self.label2.setText("Некорректные данные!")


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyWidget()
    ex.show()
    sys.exit(app.exec_())
